# Autogenerated wrapper script for SoapyLoopback_jll for aarch64-apple-darwin
export librtlsdrSupport

using soapysdr_jll
JLLWrappers.@generate_wrapper_header("SoapyLoopback")
JLLWrappers.@declare_library_product(librtlsdrSupport, "libsoapyloopback.dylib")
function __init__()
    JLLWrappers.@generate_init_header(soapysdr_jll)
    JLLWrappers.@init_library_product(
        librtlsdrSupport,
        "lib/SoapySDR/modules0.8/libsoapyloopback.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
